name: Sonarqube Analyze
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: SonarScanner for .NET Core with pull request decoration support
      uses: highbyte/sonarscan-dotnet@1.0
      with:
        sonarProjectKey: qatoolkit_qatoolkit-core-net
        sonarProjectName:  qatoolkit_qatoolkit-core-net
        sonarOrganization: qatoolkit
        dotnetBuildArguments: ./src/QAToolKit.Core/QAToolKit.Core.csproj
        dotnetTestArguments: ./src/QAToolKit.Core.Test/QAToolKit.Core.Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
        sonarBeginArguments: /d:sonar.verbose="true" /d:sonar.language="cs" /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml" /d:sonar.coverage.exclusions="**Tests.cs"
        sonarHostname: "https://sonarcloud.io"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}